- name: Install Docker
  hosts: docker_hosts
  roles:
    - role: geerlingguy.docker
  vars:
    docker_service_state: started
    docker_service_enabled: true
    docker_service_start_command: ""
    docker_restart_handler_state: restarted
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_compose_package_state: present 
    docker_install_compose: false
    docker_add_repo: true
    docker_repo_url: https://download.docker.com/linux
    docker_apt_release_channel: stable
    docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_facts.distribution | lower }}/gpg"
    docker_apt_filename: "docker"
    docker_users:
      - asmith
      - austin