---
# CIFS credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: cifs-credentials
  namespace: apps
type: Opaque
stringData:
  username: k8s
  password: Crawling8-Impending9-Stiffness2-Unsold0-Passing7
---
# TV Shows PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-tv-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeId: media-tv-pv
    volumeAttributes:
      source: //192.168.1.131/media
      subDir: TV
    nodeStageSecretRef:
      name: cifs-credentials
      namespace: apps
---
# TV Shows PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: media-tv-pv
---
# Movies PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-movies-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeId: media-movies-pv
    volumeAttributes:
      source: //192.168.1.131/media
      subDir: Movies
    nodeStageSecretRef:
      name: cifs-credentials
      namespace: apps
---
# Movies PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: media-movies-pv
---
# Downloads PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeId: media-downloads-pv
    volumeAttributes:
      source: //192.168.1.131/media
      subDir: Downloads
    nodeStageSecretRef:
      name: cifs-credentials
      namespace: apps
---
# Downloads PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: media-downloads-pv
---
# Music PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-music-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeId: media-music-pv
    volumeAttributes:
      source: //192.168.1.131/media
      subDir: Music
    nodeStageSecretRef:
      name: cifs-credentials
      namespace: apps
---
# Music PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  volumeName: media-music-pv
