apiVersion: v2
name: cert-manager
description: cert-manager - X.509 certificate management for Kubernetes
type: application
version: 1.0.0
appVersion: "v1.13.3"
home: https://cert-manager.io
sources:
  - https://github.com/cert-manager/cert-manager
maintainers:
  - name: Austin Smith
dependencies:
  - name: cert-manager
    version: v1.13.3
    repository: https://charts.jetstack.io

