app:
  dashboard_url: "https://pangolin.thewhitelodge.org"

domains:
  domain1:
    base_domain: "pangolin.thewhitelodge.org"
    cert_resolver: "letsencrypt"

server:
  secret: "your-strong-secret"

gerbil:
  base_endpoint: "152.53.52.163"

flags:
  require_email_verification: false
  disable_signup_without_invite: true
  disable_user_create_org: true
