$ANSIBLE_VAULT;1.1;AES256
61376661376430373736613166386561613465643264313661373437353432323464353137613234
6565623164303763343533623265383834376433316136350a366335616230323763336466316366
38613136343765343462643466373030633430313135353731623064313234383666663339646235
3133623462316533390a386238333735376563303063616364353530633463326563336238316265
35353866626438386633666139633737396135633931326539383530363363656238306631333738
66306332663735393430636337626566346361306661383730373064636466316239316639646461
31623838323138383364616633383535616335636631353561343663346330653765633065643938
30646563643237313764
