kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name:
  labels:

  annotations:

spec:
  parentRefs:
    - kind: Gateway
      name: 
      namespace: juypterhub

  hostnames: hub.theblacklodge.dev

  rules:
    - backendRefs:
        - name: proxy-public
          port: 80

