services:
  kestra:
    container_name: kestra
    image: kestra/kestra:latest
    pull_policy: always
    # Kestra, by default, has a termination grace period of 5m. We need to wait a little more to be sure no active tasks are running.
    stop_grace_period: 6m
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    user: "root"
    networks:
      - postgres
    command: server standalone
    volumes:
      - ${KESTRA_ROOT}:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ${KESTRA_ROOT}/tmp:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgresql:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: ${POSTGRES_PASS}
        kestra:
          # server:
          #   basic-auth:
          #     username: admin@kestra.io # it must be a valid email address
          #     password: Admin1234 # it must be at least 8 characters long with uppercase letter and a number
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8085:8080"
      - "8086:8081"

networks:
  postgres:
    external: true
    name: postgresql_postgres