version: "3.9"

services:
  homeassistant:
    image: "${HA_IMAGE}:${HA_TAG}"
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ha_config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.homeassistant.rule=Host(`${HOSTNAME_FQDN}`)"
      - "traefik.http.routers.homeassistant.entrypoints=${TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.homeassistant.tls.certresolver=${TRAEFIK_CERTRESOLVER}"
      - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

networks:
  proxy:
    external: true
    name: ${TRAEFIK_NETWORK}

volumes:
  ha_config:
    name: ha_config
