apiVersion: v2
name: minio
description: MinIO - High Performance Object Storage
type: application
version: 1.0.0
appVersion: "RELEASE.2023-12-20T01-00-02Z"
home: https://min.io
sources:
  - https://github.com/minio/minio
maintainers:
  - name: Austin Smith
dependencies:
  - name: minio
    version: 5.0.15
    repository: https://charts.min.io/

