apiVersion: v2
name: nessie
description: Nessie - Transactional Catalog for Data Lakes
type: application
version: 1.0.0
appVersion: "0.74.0"
home: https://projectnessie.org
sources:
  - https://github.com/projectnessie/nessie
maintainers:
  - name: Austin Smith
