apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dremio.fullname" . }}
  labels:
    {{- include "dremio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dremio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dremio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "dremio/dremio-oss:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: web
              containerPort: 9047
              protocol: TCP
            - name: client
              containerPort: 31010
              protocol: TCP
          env:
            - name: DREMIO_JAVA_SERVER_EXTRA_OPTS
              value: "-Dpaths.local=/opt/dremio/data/db"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: dremio-data
              mountPath: /opt/dremio/data
      volumes:
        - name: dremio-data
          emptyDir: {}
