version: "3.9"

networks:
  proxy:
    external: true
  wings0:
    name: wings0
    driver: bridge

volumes:
  wings_config:
  wings_data:
  wings_logs:
  wings_tmp:

services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.11.13
    container_name: ptero-wings
    restart: unless-stopped
    tty: true
    networks: [wings0, proxy]
    # Required for SFTP to your node (not HTTP)
    ports:
      - "2022:2022"
    environment:
      TZ: ${TZ}
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - wings_config:/etc/pterodactyl/
      - wings_data:/var/lib/pterodactyl/
      - wings_logs:/var/log/pterodactyl/
      - wings_tmp:/tmp/pterodactyl/
      - /etc/ssl/certs:/etc/ssl/certs:ro
      # If you use LE certs on the host and want Wings to terminate TLS itself, also mount:
      # - /etc/letsencrypt/:/etc/letsencrypt/:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.wings.rule=Host(`wings.${DOMAIN}`)
      - traefik.http.routers.wings.entrypoints=websecure
      - traefik.http.routers.wings.tls.certresolver=letsencrypt
      - traefik.http.services.wings.loadbalancer.server.port=8080
