- Developer:
    - Flappa:
        - abbr: TT
          href: https://github.com/
- Social:
    - Reddit:
        - icon: reddit
          href: https://reddit.com/
          description: The front page of the internet
- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
