# values.yaml
config:
  bookmarks: |
    - Dev:
        - Github:
            - abbr: TT
              href: https://github.com
  services: |
    - Media:
        - Plex:
            href: http://plex
            icon: plex
  widgets: |
    - resources:
        cpu: true
        memory: true
  settings: |
    title: My Homepage
  kubernetes: |
    mode: cluster
