apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels: { app: homepage }
spec:
  replicas: 1
  selector:
    matchLabels: { app: homepage }
  template:
    metadata:
      labels: { app: homepage }
    spec:
      volumes:
        - name: homepage-config
          configMap:
            name: homepage-config
        - name: homepage-logs
          emptyDir: {}        # Kustomize rewrites to hashed name
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: home.theblacklodge.dev
            - name: HOMEPAGE_CONFIG_DIR
              value: /app/config
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
              readOnly: true         # configs read-only
            - name: homepage-logs
              mountPath: /app/config/logs   # writable
          ports:
            - containerPort: 3000
