apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage

resources:
  - namespace.yaml
  - deployment.yaml
  - services.yaml
  - ingress.yaml

configMapGenerator:
  - name: homepage-config
    files:
      - settings.yaml
      - bookmarks.yaml
      - kubernetes.yaml
      - widgets.yaml
      - docker.yaml

generatorOptions:
  disableNameSuffixHash: false
