apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage

configMapGenerator:
  - name: homepage-config
    files:
      - bookmarks.yaml

generatorOptions:
  disableNameSuffixHash: false
