- hosts: docker_hosts
  become: true
  become_method: sudo

  tasks:
    - name: Install nfs-common (Debian/Ubuntu)
      ansible.builtin.apt:
        name: "nfs-common"
        state: present
        update_cache: true
      when: ansible_facts['distribution'] in ['Ubuntu', 'Debian']
    - name: Install nfs-utils (Rocky)
      ansible.builtin.dnf:
        name: "nfs-utils"
        state: present
      when: ansible_facts['distribution'] == 'Rocky'

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /mnt/nas_data
        state: directory
        mode: '0755'
        
    - name: Mount an NFS volume
      ansible.posix.mount:
        src: 192.168.1.131:/volume1/infrastructure/docker
        path: /mnt/nas_data
        opts: rw,sync,hard
        state: mounted
        fstype: nfs