ingress:
  enabled: true
  className: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  hosts:
    - host: zammad.theblacklodge.dev
      paths: [{ path: /, pathType: Prefix }]
  tls:
    - secretName: zammad-tls
      hosts: [zammad.theblacklodge.dev]

postgresql:
  enabled: true
  auth:
    username: zammad
    password: "<strong-password>"
    database: zammad

redis:
  enabled: true

persistence:
  enabled: true
  size: 20Gi
