apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-config
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  settings.yaml: |
    {{- toYaml .Values.config.settings | nindent 4 }}
  
  services.yaml: |
    {{- toYaml .Values.config.services | nindent 4 }}
  
  widgets.yaml: |
    {{- toYaml .Values.config.widgets | nindent 4 }}
  
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
        - ArgoCD Docs:
            - abbr: AD
              href: https://argo-cd.readthedocs.io/
    
    - Data & Analytics:
        - Dremio Docs:
            - abbr: DD
              href: https://docs.dremio.com/
        - MinIO Docs:
            - abbr: MD
              href: https://min.io/docs/
        - Apache Spark:
            - abbr: AS
              href: https://spark.apache.org/docs/latest/
    
    - Media:
        - Sonarr Wiki:
            - abbr: SW
              href: https://wiki.servarr.com/sonarr
        - Radarr Wiki:
            - abbr: RW
              href: https://wiki.servarr.com/radarr
