apiVersion: v2
name: grafana
version: 10.1.4
dependencies:
  - name: grafana
    version: 10.1.4
    repository: "https://grafana.github.io/helm-charts" #Note: this came from the install command from ArtifactHub.io
