grafana:
  ingress:
    enabled: true
    ingressClassName: "traefik" # note: field is usually ingressClassName
    annotations:
      kubernetes.io/ingress.class: "traefik"
      cert-manager.io/cluster-issuer: "letsencrypt-dns"
    path: / # single path for all hosts
    hosts:
      - grafana.theblacklodge.dev # list of strings, not maps
    tls:
      - hosts:
          - grafana.theblacklodge.dev
        secretName: grafana-tls
