apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zammad
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: zammad
  sources:
  # Source 1: the upstream chart
  - repoURL: https://github.com/zammad/zammad-helm.git
    targetRevision: main
    path: charts/zammad
  # Source 2: your infra repo containing values
  - repoURL: https://github.com/austindsmith/homelab-infra.git
    targetRevision: main
    ref: values
  helm:
    valueFiles:
      - $values/k8s/zammad/values/prod.yaml
  syncPolicy:
    automated: {}
