apiVersion: v2
name: argocd
description: ArgoCD - Declarative GitOps CD for Kubernetes
type: application
version: 1.0.0
appVersion: "v2.9.3"
home: https://argoproj.github.io/cd
sources:
  - https://github.com/argoproj/argo-cd
maintainers:
  - name: Austin Smith
dependencies:
  - name: argo-cd
    version: 5.51.6
    repository: https://argoproj.github.io/argo-helm

