apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-master
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    component: master
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: web-ui
      protocol: TCP
      name: web-ui
    - port: 7077
      targetPort: spark
      protocol: TCP
      name: spark
  selector:
    {{- include "spark.selectorLabels" . | nindent 4 }}
    component: master
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark.fullname" . }}-worker
  labels:
    {{- include "spark.labels" . | nindent 4 }}
    component: worker
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: web-ui
      protocol: TCP
      name: web-ui
  selector:
    {{- include "spark.selectorLabels" . | nindent 4 }}
    component: worker
