version: "3"

volumes:
    mysql_data:
    romm_resources:
    romm_redis_data:

services:
    romm:
        image: rommapp/romm:latest
        labels:
          com.centurylinklabs.watchtower.enable: "true"
        container_name: romm
        restart: unless-stopped
        environment:
            - DB_HOST=romm-db
            - DB_NAME=romm # Should match MARIADB_DATABASE in mariadb
            - DB_USER=romm-user # Should match MARIADB_USER in mariadb
            - DB_PASSWD=ozD3A72iomYR9DH7Vfhb # Should match MARIADB_PASSWORD in mariadb
            - ROMM_AUTH_SECRET_KEY=078b13cda707c8fd5d67abd5b81960a7f859b879b631ee1f1411910818a78900 # Generate a key with `openssl rand -hex 32`
            - SCREENSCRAPER_USER=primary.eleven077@passmail.net # These are the recommended metadata providers
            - SCREENSCRAPER_PASSWORD=4ZB5h9jSWAknjfDr0kM9 # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#screenscraper
            - RETROACHIEVEMENTS_API_KEY=rnFSK2i7HQtdfQZc1tauggdovShj01R6 # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#retroachievements
            - STEAMGRIDDB_API_KEY= # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#steamgriddb
            - HASHEOUS_API_ENABLED=true # https://docs.romm.app/latest/Getting-Started/Metadata-Providers/#hasheous
            - HTLB_API_ENABLED=true
        volumes:
            - romm_resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
            - romm_redis_data:/redis-data # Cached data for background tasks
            - /mnt/nas/roms:/romm/library # Your game library. Check https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure for more details.
            - /path/to/assets:/romm/assets # Uploaded saves, states, etc.
            - /path/to/config:/romm/config # Path where config.yml is stored
        ports:
            - 8088:8080
        depends_on:
            romm-db:
                condition: service_healthy
                restart: true

    romm-db:
        image: mariadb:latest
        labels:
          com.centurylinklabs.watchtower.enable: "true"
        container_name: romm-db
        restart: unless-stopped
        environment:
            - MARIADB_ROOT_PASSWORD=Uf2R0NtAvyipjcj2T126 # Use a unique, secure password
            - MARIADB_DATABASE=romm
            - MARIADB_USER=romm-user
            - MARIADB_PASSWORD=ozD3A72iomYR9DH7Vfhb
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
            start_period: 30s
            start_interval: 10s
            interval: 10s
            timeout: 5s
            retries: 5