apiVersion: v1
kind: Service
metadata:
  name: {{ include "airbyte.fullname" . }}-webapp
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
    component: webapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    component: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "airbyte.fullname" . }}-server
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
    component: server
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airbyte.selectorLabels" . | nindent 4 }}
    component: server
